### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by prashsamosa** [RaddyTheBrand/55_NextRivals-NextJs-Retro-Arcade-Website#1]
Raddy I am getting these errors during categories section 
first one is whenever i click on any category suppose arcade 
![Screenshot 2024-10-26 042210](https://github.com/user-attachments/assets/b92e7909-1cae-4c0a-a4d4-152f38a53ea8)
second error is when I am at Home / Arcade / Cadillacs and Dinosaurs if I click on Arcade 
![Screenshot 2024-10-26 042346](https://github.com/user-attachments/assets/f9f8991d-d94a-43fd-9fba-7f339b1fa16a)
I am about this arcade 
![Screenshot 2024-10-26 042426](https://github.com/user-attachments/assets/9dd188d5-3b57-49b7-86aa-2769026602c6)

I have tried in v14 and v15 getting these errors.

**Comment by prashsamosa** [comment]
https://github.com/user-attachments/assets/7af036e1-4de4-4fa9-b075-ad1ec7e6f94d

**Comment by RaddyTheBrand** [comment]
Can you try adding await before getting the searchParam:
`const page = await parseInt(searchParams.page) || 1;`

For the other error "{game.categories[0]?.title}", console log game and game.categories just to check if you are getting the data. You can also always add `?` between game and categories.
`{game?.categories[0]?.title}`

I hope the await fixes the issue for you.

**Comment by prashsamosa** [comment]
Thanks Mr Raddy.
